import requests
import os
from dotenv import load_dotenv, set_key
from typing import Optional, List, Tuple
from datetime import date, datetime

load_dotenv()
# compute default as previous month (wrap to 12 if current month is January)
today: date = date.today()
default_month: int = today.month - 1 if today.month > 1 else 12
CURRENT_MONTH: str = os.getenv("CURRENT_MONTH", str(default_month))
CURRENT_VERSION: int = int(os.getenv("CURRENT_VERSION", "0")) # pyrefly: ignore


def url(number: int):
    return f"https://cdn.posit.co/positron/dailies/win/x86_64/Positron-2025.{CURRENT_MONTH}.0-{number}-Setup-x64.exe"


class bcolors:
    OKGREEN = "\033[92m"
    WARNING = "\033[93m"
    ENDC = "\033[0m"


def check_downloadable(url: str) -> int:
    try:
        # Send a HEAD request to the URL
        response = requests.head(url)

        # Check if the response status code is 200 (OK), indicating the file is available
        return response.status_code
    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")
        return -1


def generate_readme(available_versions: List[Tuple[int, str]]):
    """Generate README.md with a table of available Positron dailies."""
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
    
    readme_content = f"""# Positron Daily Builds

This repository tracks available Positron daily builds.

## Latest Available Dailies

Last updated: {current_time}

| Version | Month | Build Number | Download Link |
|---------|-------|--------------|---------------|
"""
    
    for version_num, download_url in available_versions:
        readme_content += f"| 2025.{CURRENT_MONTH}.0-{version_num} | {CURRENT_MONTH} | {version_num} | [Download]({download_url}) |\n"
    
    if not available_versions:
        readme_content += "| No builds available | - | - | - |\n"
    
    readme_content += "\n## About\n\n"
    readme_content += "This list is automatically generated by scanning the Positron CDN for available daily builds.\n"
    
    return readme_content


def write_readme(content: str):
    """Write content to README.md file."""
    with open("README.md", "w") as f:
        f.write(content)


def main():
    latest_version: Optional[int] = None
    available_versions: List[Tuple[int, str]] = []
    
    try:
        for i in range(CURRENT_VERSION, CURRENT_VERSION + 50):
            build_url = url(i)
            match check_downloadable(build_url):
                case 200:
                    latest_version = i
                    available_versions.append((i, build_url))
                    print(bcolors.OKGREEN + f"{i}: downloadable: {build_url}" + bcolors.ENDC)
                case 404 | 403:
                    print(f"{i}: not downloadable.")
                case _:
                    print(bcolors.WARNING + f"{i}: unknown response." + bcolors.ENDC)
    except KeyboardInterrupt:
        print("\nProcess interrupted by user. Exiting...")
    
    if latest_version is not None:
        set_key(".env", "CURRENT_VERSION", str(latest_version))
        print(f"Latest downloadable: {url(latest_version)}")
    
    # Generate and write README.md
    if available_versions:
        readme_content = generate_readme(available_versions)
        write_readme(readme_content)
        print(f"\nREADME.md generated with {len(available_versions)} available version(s).")


if __name__ == "__main__":
    main()
